using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace ResponseCacheDemo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DefaultController : ControllerBase
    {
        [HttpGet]
        [Route("index/{name}")]
        [ResponseCache(Duration = 60)]
        public string Index(string name)
        {
            return ReturnResponse("Index" + name);
        }

        [HttpGet]
        [Route("home/{name}")]
        public string Home(string name)
        {
            return ReturnResponse("Home" + name);
        }

        private string ReturnResponse(string name)
        {
            return $"Response generated by {name} at {DateTime.Now}";
        }
    }
}
